CLOUD_CONFIG_PATH = File.join(File.dirname(__FILE__), "nocloud.iso")

Vagrant.configure("2") do |config|
  config.vm.base_mac = nil
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vbguest.auto_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.define "stretch" do |n|
    n.vm.hostname = "eni-ifupdown" 
    n.vm.network "forwarded_port", guest: 22, host: 2001
    n.vm.network "private_network", auto_config: false, ip: "192.168.0.1", hostname: true
    n.vm.box = "debian/stretch64"
  end

  config.vm.define "buster" do |n|
    n.vm.hostname = "systemd-networkd"
    n.vm.network "forwarded_port", guest: 22, host: 2002
    n.vm.network "private_network", auto_config: false, ip: "192.168.0.1", hostname: true
    n.vm.box = "debian/buster64"
  end

  config.vm.define "focal" do |n|
    n.vm.hostname = "netplan"
    n.vm.network "forwarded_port", guest: 22, host: 2003
    n.vm.network "private_network", auto_config: false, ip: "192.168.0.1", hostname: true
    n.vm.box = "ubuntu/focal64"
  end

  config.vm.define "bionic" do |n|
    n.vm.hostname = "cloud-init"
    n.vm.network "private_network", auto_config: false, ip: "192.168.0.1", hostname: true, mac: "080027a45905"
    n.vm.box = "ubuntu/bionic64"
    n.vm.provider "virtualbox" do |v|
      v.customize [ "storageattach", :id, "--storagectl", "SCSI", "--port", "1", "--type", "dvddrive", "--medium", CLOUD_CONFIG_PATH ]
   end   
  end

  config.vm.define "arch" do |n|
    n.vm.hostname = "netctl"
    n.vm.network "forwarded_port", guest: 22, host: 2005
    n.vm.network "private_network", auto_config: false, ip: "192.168.0.1", hostname: true
    n.vm.box = "archlinux/archlinux"
  end

  config.vm.define "centos" do |n|
    n.vm.hostname = "sysconfig"
    n.vm.network "forwarded_port", guest: 22, host: 2006
    n.vm.network "private_network", auto_config: false, ip: "192.168.0.1", hostname: true
    n.vm.box = "centos/8"
  end
end
